# Generated by Django 5.0.3 on 2024-11-20 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'AgencyType',
                'verbose_name_plural': 'AgencyTypes',
            },
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('seats_num', models.IntegerField()),
            ],
            options={
                'verbose_name': 'BodyType',
                'verbose_name_plural': 'BodyTypes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='RiskClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'RiskClass',
                'verbose_name_plural': 'RiskClasses',
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'RiskType',
                'verbose_name_plural': 'RiskTypes',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True)),
                ('usage_type', models.CharField(choices=[('private', 'Private'), ('corporate', 'Corporate'), ('motorcycle', 'MotorCycle')], default='private', max_length=10)),
                ('person_entitled_note', models.TextField(blank=True)),
                ('limitation_note', models.TextField(blank=True)),
                ('exclusions_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'VehicleMake',
                'verbose_name_plural': 'VehicleMakes',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_class', to='setups.riskclass')),
            ],
            options={
                'verbose_name': 'DiscountType',
                'verbose_name_plural': 'DiscountTypes',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('basic_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_seats', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_peril', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ecowas_peril', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pa_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sticker_fee', models.DecimalField(decimal_places=2, default=23.0, max_digits=10)),
                ('brown_card_sticker_fee', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('excess_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ecowas_peril_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('basic_premium_delta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('minimum_premium', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('comprehensive_min_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('comprehensive_max_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('comprehensive_excess_constant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('third_party_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('third_party_limit', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10)),
                ('third_party_fire_min_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('third_party_fire_max_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.schedule')),
            ],
            options={
                'verbose_name': 'Tariff',
                'verbose_name_plural': 'Tariffs',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make', to='setups.vehiclemake')),
            ],
            options={
                'verbose_name': 'VehicleModel',
                'verbose_name_plural': 'VehicleModels',
            },
        ),
    ]
